services:
  - type: web
    name: skyfall-made-by-patryk
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: JWT_SECRET
        generateValue: true
